apiVersion: batch/v1
kind: Job
metadata:
  namespace: athena-cluster
spec:
  ttlSecondsAfterFinished: 5
  template:
    metadata:
      labels:
        app: athena-agent
    spec:
      containers:
      - name: athena
        image: athena:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: '1'
            memory: 500Mi
      restartPolicy: Never

