name: isServiceToken
type: plugin #/chakramProperty/chakramMethod
context: global # contexts: global, [suiteName] or [testName] for isolation
config:
  type: lib #/inline
  path: plugins/generatedPlugin.js #or inline function
  exposes: serviceToken