apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: sidecar-nginx
        image: atrifan/athena:v1
        hostNetwork: true
        hostPid: true
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        command: ["npm"]
        args: ["run", "sidecar-test"]
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: envoy-conf
            mountPath: /etc/envoy/config
          - name: perf-conf
            mountPath: /etc/tests
    volumes:
      - name: envoy-conf
        configMap:
          name: envoy-conf
      - name: perf-conf
        configMap:
          name: perf-conf