apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: sidecar-nginx
        image: ciuca/pinger:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080