apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.morven.me
    clientConfig:
      service:
        name: sidecar-injector-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1UQXlOekV5TURNeE5Wb1hEVEk1TVRBeU5URXlNRE14TlZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXZOCmFnNkhZWHJOeVR4am1zTWhhODlUaTZ5UFJkWmNJMnNUTWNWTDZ6d1JmTVdRUzBGeUFyVjFmaHNNZk8rNXBJMDEKZTJuOVZVczF3Vm96N1lJSUh1QVZFYzJyNFdTUVNBaU1GaFpIcncydmFUTllxZFVyNVpFdjBJZk81U1hDWUJaNwp1VEpvZkR6d3h0dllnN25GeXpRWTR5dU9DRzFuNzNxVTNFMEJoSFJYcGFzdzFOYnVMSDZkVWh1TUliNEVTTHlhCnhXTWpBMGp2UVRoZmtla0Z3Z1B4eHE0QkxaZXpBcGF4bWh0c2RURnM0ek00aE56RjJIelI0REFoN0E5V2hNWUMKdXcya2lCc2cxelBnYVBPRjZ5L1hXc0Y0YzEwaGlEL0JiZHphRE85SUxtZG5aekczOThuYWt6Um12OTFFV1VuRwowckRMRWk2RFNmVVh2WjB5ODJzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBd2NqSTN0TUdwem54NitWT2JIck5qL1Q0bWZadEdYK29FRFVVVW0rVmV5N2hyM2dmWgoxeVFqWndLcWM3TlA1eGVGWE5CVS9ReHE0NGpkS0JDZ3ovWWd6VVhFZ25lR0c4dnBRTjRYVDF5SjJ4MnFJdWFGCnRMU2E1K3VFS041REV5QnRCU21yZ3IvWWMvWmZIVlkrNTY1UWZsTXp3NEpNSzZidXVQVm9kMm40c2swZ1RKQWQKdzlkeTdIZG8rTWhVbkhaZXVteGhqeTNsN3Jha2JwOTdvT3gxanI5OGpsWWxMOXZ5WHVaWHNJNDVGNEtpK0dMeQpnWUhKZ0ZpSllJMENCNCtSUUhZRmw1cXduWmNYOFVwTEwzb1h2Wi9pYmFZbkpkSEJUVjhTL2N3OG5lZ2xWNWt2Cms1WWpGVjgxZWwva2d0R2x6SmdNK2JFc3NqZVM0T2lkZi9qOAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled
