 // Create
 export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
 export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
 export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';

 // Read
 export const READ_PROJECTS_REQUEST = 'READ_PROJECTS_REQUEST';
 export const READ_PROJECTS_SUCCESS = 'READ_PROJECTS_SUCCESS';
 export const READ_PROJECTS_ERROR = 'READ_PROJECTS_ERROR';

 // Update
 export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
 export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
 export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';

 // Toggle
 export const TOGGLE_PROJECTS_MODAL = "TOGGLE_PROJECTS_MODAL";
 
 // Change New Project Modal Field Values
 export const CHANGE_PROJECT_DESCRIPTION = "CHANGE_PROJECT_DESCRIPTION";
 export const CHANGE_PROJECT_NAME = "CHANGE_PROJECT_NAME";
 export const CHANGE_PROJECT_REPO_NAME = "CHANGE_PROJECT_REPO_NAME";

 export const READ_SINGLE_PROJECT = "READ_SINGLE_PROJECT"
 export const UPDATE_PERF_JOB_CONTENTS = "UPDATE_PERF_JOB_CONTENTS"

 export const READ_PERF_TESTS_SUCCESS = "READ_PERF_TESTS_SUCCESS"
 export const READ_PERF_TEST_RUNS_SUCCESS = "READ_PERF_TEST_RUNS_SUCCESS"
 export const READ_PERF_TEST_DETAILS_SUCCESS = "READ_PERF_TEST_DETAILS_SUCCESS"

 export const SCHEDULE_PERF_TEST_RUN_SUCCESS = "SCHEDULE_PERF_TEST_RUN_SUCCESS"
 export const READ_SINGLE_PERF_TEST_DETAILS_SUCCESS = "READ_SINGLE_PERF_TEST_DETAILS_SUCCESS"